### ISSUE TITLE
Where is python3-wx?

### ISSUE THREAD

**Issue by J-Kappes** [Nachtwind/rcmGUI-linux#1]
All I've found is a package called `wxPython`. I installed it, extracted fusee-launcher into the eponymous folder, put `hekate.bin` in the payloads folder and ran  `sudo python3 rcmGUI.py`. The output I received is:
```python
Traceback (most recent call last):
  File "/home/rj/Projects/rcmGUI-linux/rcmGUI.py", line 123, in OnInit
    self.frame = MyFrame(None, wx.ID_ANY, "")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rj/Projects/rcmGUI-linux/rcmGUI.py", line 32, in __init__
    self.__do_layout()
  File "/home/rj/Projects/rcmGUI-linux/rcmGUI.py", line 81, in __do_layout
    sizer_2.Add(self.btnINJ, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
wx._core.wxAssertionError: C++ assertion "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed at /tmp/pip-install-3w6fuemf/wxpython_105631054d4348328a6324798d9667f9/ext/wxWidgets/src/common/sizer.cpp(2288) in DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers
```
I run Fedora 38 btw

**Comment by danielbenitobravo** [comment]
Hello, any update on this?
